version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: centos:7
      - image: postgres:11
        name: postgres
        environment:
          POSTGRES_USER: statink
          POSTGRES_PASSWORD: statink
          POSTGRES_DB: statink
          POSTGRES_INITDB_ARGS: "-E UTF-8 --locale=en_US.UTF8 -k"

    steps:
      - run: yum update -y
      - run: yum install -y curl epel-release gnupg2 scl-utils 'http://rpms.famillecollet.com/enterprise/remi-release-7.rpm'
      - run: curl -fsSL 'https://rpm.nodesource.com/setup_11.x' | bash -
      - run: yum-config-manager --add-repo 'https://rpm.fetus.jp/jp3cki.repo'
      - run: yum-config-manager --disable jp3cki*
      - run: yum-config-manager --enable jp3cki jp3cki-h2o-mainline
      - run: yum install -y ImageMagick brotli diff gcc-c++ gearmand git gzip h2o jpegoptim make nodejs patch php73-php-cli php73-php-fpm php73-php-gd php73-php-intl php73-php-json php73-php-mbstring php73-php-mcrypt php73-php-opcache php73-php-pdo php73-php-pecl-gearman php73-php-pecl-msgpack php73-php-pecl-zip php73-php-pgsql php73-php-process php73-php-xml php73-runtime supervisor unzip
      - checkout
      - restore_cache:
          keys:
            - php-dependencies-v1-{{ checksum "composer.lock" }}
            - php-dependencies-v1-
      - restore_cache:
          keys:
            - js-dependencies-v1-{{ checksum "package-lock.json" }}
            - js-dependencies-v1-
      - run: scl enable php73 -- make check-syntax
      - run: scl enable php73 -- make init
      - save_cache:
          key: php-dependencies-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - save_cache:
          key: js-dependencies-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: scl enable php73 -- ./yii secret/db postgres statink
      - run: scl enable php73 -- make
      - run: scl enable php73 -- make -j3 check-style
